### ISSUE TITLE
Make typo styles global

### ISSUE THREAD

**Issue by JulsD** [JulsD/React-study#2]

**Comment by phts** [comment]
Regarding [`import '../styles/common.css';`](https://github.com/JulsD/React-study/blob/1752d4e739d3d27689dacb8681570810eb89a7e2/src/app/index.jsx#L6)

Currently this line is useless because common.css file has only local css rules and is imported directly in every place where it is used. It seems it was committed by a mistake when I showed an example how to use global styles. After converting common styles to global this line will have sense. 

Moreover it is a wrong place. Idea was that App is a component, like any other. And it should not be responsible for loading global styles from external folder. In our case [a script which executes the app] (https://github.com/JulsD/React-study/blob/master/src/app.jsx) should be responsible for that or somewhere around it.

----
Useful info about `:global` - https://github.com/webpack-contrib/css-loader#modules

**Comment by phts** [comment]
You forgot about [`import '../styles/common.css';`](https://github.com/JulsD/React-study/blob/1752d4e739d3d27689dacb8681570810eb89a7e2/src/app/index.jsx#L6)
